services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      MYSQL_DATABASE: franchisesDB
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchises
    ports:
      - "8080:8080"
    environment:
      - ACTIVE_PROFILE=dev
      - DB=mysql
      - DB_URL=mysql
      - DB_PORT=3306
      - DB_SCHEMA=franchisesDB
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
