package com.pragma.challenge.franchises.domain.enums;

import com.pragma.challenge.franchises.domain.constants.ConstantsMsg;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ServerResponses {
  BAD_REQUEST("E000", 400, ConstantsMsg.BAD_REQUEST_MSG),
  SERVER_ERROR("E001", 500, ConstantsMsg.SERVER_ERROR_MSG),
  FRANCHISE_CREATED_SUCCESSFULLY("", 201, ConstantsMsg.FRANCHISE_CREATED_SUCCESSFULLY_MSG),
  FRANCHISE_ALREADY_EXISTS("E002", 409, ConstantsMsg.FRANCHISE_ALREADY_EXISTS_MSG),
  BRANCH_ADDED_TO_FRANCHISE_SUCCESSFULLY(
      "", 201, ConstantsMsg.BRANCH_ADDED_TO_FRANCHISE_SUCCESSFULLY_MSG),
  FRANCHISE_NOT_FOUND("E003", 404, ConstantsMsg.FRANCHISE_NOT_FOUND_MSG),
  BRANCH_ALREADY_EXISTS("E004", 409, ConstantsMsg.BRANCH_ALREADY_EXISTS_MSG),
  PRODUCT_CREATED_SUCCESSFULLY("", 201, ConstantsMsg.PRODUCT_CREATED_SUCCESSFULLY_MSG),
  BRANCH_NOT_FOUND("E005", 404, ConstantsMsg.BRANCH_NOT_FOUND_MSG),
  PRODUCT_ALREADY_EXISTS("E006", 409, ConstantsMsg.PRODUCT_ALREADY_EXISTS_MSG),
  PRODUCT_DELETED_SUCCESSFULLY("", 200, ConstantsMsg.PRODUCT_DELETED_SUCCESSFULLY_MSG),
  PRODUCT_NOT_FOUND("E007", 404, ConstantsMsg.PRODUCT_NOT_FOUND_MSG),
  PRODUCT_UPDATED_SUCCESSFULLY("", 200, ConstantsMsg.PRODUCT_UPDATED_SUCCESSFULLY_MSG),
  TOP_PRODUCT_FOUND_SUCCESSFULLY("", 200, ConstantsMsg.TOP_PRODUCT_FOUND_SUCCESSFULLY_MSG),
  BRANCH_UPDATED_SUCCESSFULLY("", 200, ConstantsMsg.BRANCH_UPDATED_SUCCESSFULLY_MSG),
  FRANCHISE_UPDATED_SUCCESSFULLY("", 200, ConstantsMsg.FRANCHISE_UPDATED_SUCCESSFULLY_MSG);

  private final String code;
  private final int httpStatus;
  private final String message;
}
