spring:
  webflux:
    base-path: /franchises
  r2dbc:
    url: r2dbc:${DB}://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: jdbc:${DB}://${DB_URL}:${DB_PORT}/${DB_SCHEMA}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
      base-path: /
      path-mapping:
        health: actuator/health
        metrics: actuator/metrics
        loggers: actuator/loggers
  endpoint:
    health:
      probes:
        enabled: false
      show-details: "always"
  health:
    diskspace:
      enabled: false
    r2dbc:
      enabled: true
    ping:
      enabled: false
    refresh:
      enabled: false
